### ISSUE TITLE
Installing / Building?

### ISSUE THREAD

**Issue by rosscarlson** [pre-martin/SimHubPropertyServer#28]
The install guide says to "simply copy PropertyServer.dll into the root directory" - yet I can't find that file in the project. I assume that means I need to compile it but as I'm not done that before I'm not really sure where to start. Can you not provide a pre-compiled version of PropertyServer.dll or can you give me instructions on what I need to do to compile it?

If this is a stupid question my apologies.

**Comment by rosscarlson** [comment]
I AM A MORON! I just saw the "releases" section with what I need, I'm so sorry for the stupid post.

Closing now.

**Comment by pre-martin** [comment]
You are not the first one with this problem. As I am working almost every day with systems like GitHub, it never came to my mind that the download could be a problem. I will update the start page and point to the "Releases" section on the right.
