### ISSUE TITLE
As reported on your Youtube

### ISSUE THREAD

**Issue by doc3d** [pre-martin/SimHubPropertyServer#36]
I managed to get both plugins installed and looking like they are working. My issue is what do I do then? If I understood correctly, I need vJoy so that I can create a virtual controller in Simhub, and link this to the stream deck, would that be correct? I installed vJoy (but it seemed to hang at the end, I had to force quit the installer. But it shows the monitor, configure etc, so I hope it installed correctly.  However, I have no clue how to set up the vJoy controller, or how to pair that to the Deck. Then it’s the commands. Again, if I understood correctly, you can make up anything you want, as long as you call it the same thing in Hub, and link that to a keyboard command? This is also something I have absolutely no clue about…

you mentioned you would create a tutorial video? That would be extremely helpful, especially if you go from the very beginning and show all steps, especially in the configuration. Thank you for the kind support. Hopefully I can get this sorted as it seems extremely useful. 

-doc3d

**Comment by pre-martin** [comment]
Hi,

vJoy is not essential. There are basically two different functions implemented in my plugins:

1. Display some information from SimHub on a Stream Deck button
2. Press a button on the Stream Deck and trigger some action in the simulation or in SimHub

Let's assume that you have dragged my "Hotkey" onto a Stream Deck button in the Stream Deck software.

## Display some information from SimHub on a Stream Deck button

The first function works by searching for the appropriate property in SimHub and entering it in the "SimHub Property" field in the section "State" and/or "Title". For example you can enter `dcp.gd.EngineStarted` in the section "State". Now your Stream Deck button turns green when the engine is running, and red when the engine is turned off. You can (and should) adjust the icons of the button. There are some examples in https://github.com/pre-martin/StreamDeckSimHubPlugin/tree/main/Icons

## Press a button on the Stream Deck and trigger some action in the simulation or in SimHub

The second function can be divided further into

a. Trigger something in the simulation (like turning the engine on or off). This can be achieved by either sending a keystroke ("Hotkey") to the currently active window or by using the SimHub Control Mapper.
b. Trigger something in SimHub (like switching a dash screen or incrementing the volume for a ShakeIt Bass effect). This can be achieved by either using a "SimHub Control" or by using the SimHub Control Mapper.

So there are three options: Keystroke ("Hotkey"), "SimHub Control" and "SimHub Role Mapper". Here are the details:

### Sending a keystroke ("Hotkey") to the currently active window:

Let's stay with the example of the engine. In ACC this would be the key "S" that has to be sent to the simulation. So simply enter "S" in my Stream Deck "Hotkey" into the field "Hotkey". Here are screenshots for this example: https://github.com/pre-martin/StreamDeckSimHubPlugin/blob/main/doc/hotkey/Hotkey.adoc#button-to-toggle-the-engine-in-acc If you press the Stream Deck button, the keystroke "S" will be sent to the currently active window (your simulation) and will toggle the engine, if it is ACC.

### Using a "SimHub Control" to trigger some functionality in SimHub:

Simply enter a string - whatever you like - in my Stream Deck "Hotkey" into the field "SimHub Control". Let's assume that you want to increment the volume of a ShakeIt Bass effect. So just enter "Increment volume" (or whatever you like) into this field. This "SimHub Control" now has to be assigned in SimHub to the effect. Details with screenshots can be found here: https://github.com/pre-martin/StreamDeckSimHubPlugin/blob/main/doc/shakeit/ShakeIt.adoc#buttons-for-and and the assignment is shown on the same page just one section further below.

### Using the "SimHub Role Mapper"

This is finally the option where you *can* use vJoy. The SimHub Control Mapper is a SimHub feature and it adds a layer of abstraction to your input devices. You can combine different sources (Wheel 1, Wheel 2, some buttons of my Stream Deck plugin) into one logical device and only assign this logical device in your simulation. This approach solves three problems:

1. Keystrokes are only sent to the currently active window. This is usually your simulation, but if you are streaming, it could also happen that your streaming software is the currently active window. But you don't want to send the "S" of the toggle engine function to your streaming software.
2. If you have different wheels, the simulation sees them as different input devices. So usually you have to switch input profiles in your simulation if you are switching wheels. This is cumbersome.
3. Usually you can map only one input device to one function in the simulation. What if you would like to toggle the engine with all out of (a) button on the wheel (b) button on your button box (c) button on your Stream Deck? You cannot map all three of them to the same function in the simulation.

So, the SimHub Control Mapper solves several problems that you may have. But is is more complex to configure and it requires either vJoy or an Arduino Pro Micro attached to your PC. I will explain this feature later.

**Comment by pre-martin** [comment]
You cannot control the ShakeIt profiles itself, but most elements inside of a profile. Wherever you find "Assign Controls" in SimHub, you can use your Stream Deck to control this particular SimHub function.

Please see the screenshots that I have linked above in the section "Using a SimHub Control ...". Chapter 4.3 shows the "Assign" dialog in SimHub. My plugin shows as "Property Server" and it should appear with a green "Enabled" flag. Now if you enter `SomeFunnyText` in Stream Deck into the field "SimHub Control" (Hotkey or Input Trigger), it should appear in the "Assign" dialog as `PropertyServerPlugin.SomeFunnyText`, if you press that Stream Deck key.

AC + Turn indicator: I think that I already mentioned on YouTube, that AC only delivers a limited set of data. It does not deliver any data about lights. So unfortunately, there is no feedback possible.

**Comment by doc3d** [comment]
I did hear you say that in the video. What I thought possible was to use a simple keystroke. That if key X is pressed, either from the wheel or on the stream deck, the button changes from A to B, or would that not be possible either? If so, Im sorry for misunderstanding that part. Its not really important if Simhub "understands" what command you are trying to execute, I only need it to register the button-press on my wheel to light up button X on the SD. 
Im not at home ATM so cant test right now, but will give it a shot once I get home. 

If all else fails I can still use it with ACC, only stressing this since at the moment, I use AC way more than ACC.

**Comment by pre-martin** [comment]
I'm not at home right now either, so only a short answer.

IMHO you need some property in SimHub which tracks the on/off state. As this property is not updated by the simulation (because AC does not deliver this data), some logic has to be added. Like "if game loaded, reset to 'off'". Or "if new race starts, reset to 'off'". Then, on every button / keypress, the state has to be toggled, too. In theory, this property should now be as close as possible in sync with the actual light state in AC.

There is only one problem: AFAIK there is no possibility in SimHub to define logic outside of the "Dash" feature. A new plugin would have to be implemented.

I will ask on the SimHub Discord channel if there is some better approach to this problem. Because LFM started to support AC, I see a greater need for this feature.

**Comment by doc3d** [comment]
I agree. I think the multi-Class races on LFM will be very popular, and they already have 2-3 series with multi-class. Ive tried using a mod in AC that gives you "blinker-sound" but its hit or miss and doesnt always work. Not being able to tell from inside the car if your turn-signal is on or off is less than ideal, which is why I wanted to check this in the first place. As a fall-back I can still use the SD button, its just a bit risky taking my hand off the wheel given the circumstances I need to use the blinker :)
Anyways, thank you for checking this. I have also talked to the developer of a great app called Simulator Controller, which also does StreamDeck integration, but is more focused on Race Assistants and Race management. He said he would look into this as well, so there might be a solution for this in the future.

**Comment by pre-martin** [comment]
Closing this one.
